### ISSUE TITLE
Buffer() Deprecation

### ISSUE THREAD

**Issue by invaderb** [mcollina/coap-packet#10]
Greetings!

I noticed that Buffer() is still being used in the index.js on line 2 and 43 which appear to be just allocating size.

I changed them to Buffer.alloc() and everything still seems to work as intended. Unless I'm reading the code incorrectly would it be possible to update those?

(node:50857) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead

**Comment by mcollina** [comment]
This module is really old. It will need a significant maintainance to get it up speed... and I do not have that amount of time.

**Comment by invaderb** [comment]
Darn that's unfortunate since I do see some dependency on node-coap with this.

**Comment by mcollina** [comment]
If you want to send a PR that updates the deps, update CI, etc..
