### ISSUE TITLE
Option does not follow the specs

### ISSUE THREAD

**Issue by dimircea** [mcollina/coap-packet#7]
Hi,

First, thank you for the good work so far!

Now the issue: the structure of the options is not according with the CoAP specs v18. According with the specs, the Option Delta Extended (0-2 bytes) and Option Length Extended (0-2 bytes) are used only if the 4bit Option Delta and respectively 4bit Option Length values are greater than value 12. This means, the Option Header is composed of 1 mandatory byte and 0-4 bytes based on the 2 values stored by the first byte. The implementation of this module adds by default 5 bytes plus value, which makes this module incompatible with applications that follows the specs in CoAP message encoding ( as my on the go CoAP library I write for AVR MCUs with 2k ram or less for being used with small IoT sensor/actuator nodes).

Best regards,
Mircea.

**Comment by mcollina** [comment]
Thanks so much for noting this! I am really low bandwidth at the moment,
would you (or anybody else) submit a PR for solving this issue?

Thank so much again!
Il giorno mer 18 feb 2015 alle 10:33 dimircea <notifications@github.com> ha
scritto:

**Comment by dimircea** [comment]
I am sorry, seems that I was wrong afterwards. After looking carefully at your JS code, looks that the problem was not this, but rather a transmission error which incidentally added (not sure how and why, maybe because I am behind a proxy...)  3-to-5 '00000000' bytes, that mixing up the CoAP packet and resulting in the case where it looked like the 4 bytes comes from the 4 extra option bytes (I had only one option). Now I moved the code to another server (since the other one is down for repairing) and ...surprise! The same code works just fine.

I close this issue now. Thanks for your answer anyway and thanks for your great job!

Just a small advice ( from programmer to programmer :) ): it is good if you use ";" as line terminator in your JS code because in some situations this can cause hard to detect logic errors. E.g., when using 'return' and the returned value/expression is on the next line without ";" you actually return 'undefined'. JSLint also complain about missing ";".

Best regards,
Mircea.
